mappings:
  axes:
    - axes[0]
    - axes[1]
    - axes[2]
    - axes[3]
    - axes[4]
    - axes[5]
    - axes[6]
    - axes[7]
  buttons:
    - buttons[8]
    - buttons[10]
    - buttons[11]
    - buttons[9]
    - buttons[6]
    - buttons[7]
    - buttons[4]
    - buttons[5]
    - buttons[3]
    - buttons[2]
    - buttons[1]
    - buttons[0]
    - buttons[12]
